/* 0928B · 台北過夜後由同一架飛對號班（使用者：「0928 飛 KX108 要緊接 0927 KX107，為什麼反而是去隔壁」）
   輪轉的「平均分派」把每一個台北進出的勤務各自交給當月班最少的飛機，飛機在台北過夜後身分就斷了
   （實測 60 天裡 KX107→隔天 KX108 天天換飛機；全網同樣情形 93%）。
   做法：分派完成後，照時間順序檢查每一個「N 號從 P 站飛回台北」：30 小時內從台北飛回 P 站的 N±1（或同號）
   如果是另一架同機型 B 在飛，就把兩架「從這裡以後的班表」整段對調 —— 兩架當下都停在台北，
   每一段航班、每一個勤務、接續都原封不動，只是換哪一架飛；對調前確認不會重疊。
   有松山派駐、維修、新增投入日或退役日的飛機不參與對調。 */
RL('tpe swap','kgm-0823o-r72',
"  live.forEach(function(t){distOut[t].sort(function(a,b){return a.depAbs-b.depAbs})});\n  out=distOut;",
"  live.forEach(function(t){distOut[t].sort(function(a,b){return a.depAbs-b.depAbs})});\n  try{swapPairs928(distOut)}catch(e){try{console.warn('0928B swap',e)}catch(_){}}\n  out=distOut;",1);
RL('tpe swap fn','kgm-0823o-r72',
"  function num72(c){var m=/(\\d+)/.exec(String(c||''));return m?+m[1]:-1}",
"  function num72(c){var m=/(\\d+)/.exec(String(c||''));return m?+m[1]:-1}\n  function swapPairs928(dist){\n    var skip={};\n    try{Object.keys(S.tsaWindowsR913||{}).forEach(function(t){skip[t]=1})}catch(_){}\n    try{(S.fleetMaintenanceR830||[]).forEach(function(m){if(m&&m.tail)skip[m.tail]=1})}catch(_){}\n    try{Object.keys(S.fleetRetiredR928||{}).forEach(function(t){skip[t]=1});(S.fleetAddedR928||[]).forEach(function(a){if(a&&a.reg)skip[a.reg]=1})}catch(_){}\n    try{Object.keys(S.tsaFleet||{}).forEach(function(t){skip[t]=1})}catch(_){}\n    var tl=live.filter(function(t){return !skip[t]&&dist[t]});\n    function frOf(q){return sta(q.fr||String(q.route||'').split('\\u2192')[0])}\n    function toOf(q){return sta(q.to||String(q.route||'').split('\\u2192')[1])}\n    var owner=new Map(),deps={},arrs=[];\n    tl.forEach(function(t){dist[t].forEach(function(q){owner.set(q,t);\n      if(q.noPax)return;\n      if(frOf(q)==='TPE')(deps[toOf(q)]=deps[toOf(q)]||[]).push(q);\n      if(toOf(q)==='TPE')arrs.push(q)})});\n    Object.keys(deps).forEach(function(k){deps[k].sort(function(a,b){return a.depAbs-b.depAbs})});\n    var avg928=tl.length?tl.reduce(function(a,t){return a+dist[t].length},0)/tl.length:0;\n    arrs.sort(function(a,b){return a.arrAbs-b.arrAbs});\n    var n=0,tried=0;\n    arrs.forEach(function(r){\n      var A=owner.get(r);if(!A)return;\n      var P=frOf(r),m=num72(r.code);if(m<0)return;\n      var L=deps[P]||[],y=null;\n      /* 先找對號班（回程單號 N → 去程 N+1，例如 KX107 → 隔天 KX108），找不到才用同號或 N±1 */\n      var pm928=(m%2)?m+1:m-1,y2=null;\n      for(var i=firstAt(L,r.arrAbs+TURN72);i<L.length;i++){var c=L[i];if(c.depAbs>r.arrAbs+1800)break;var k=num72(c.code);if(k===pm928){y=c;break}if(!y2&&(k===m||Math.abs(k-m)===1))y2=c}\n      if(!y)y=y2;\n      if(!y)return;\n      var B=owner.get(y);if(!B||B===A)return;\n      tried++;\n      var LA=dist[A],LB=dist[B],ia=LA.indexOf(r),iy=LB.indexOf(y);if(ia<0||iy<0)return;\n      var nA=LA[ia+1],pB=LB[iy-1];\n      /* 兩架都要停在台北：A 剛落地台北；B 的上一段也要落在台北 */\n      if(pB&&toOf(pB)!=='TPE')return;\n      if(pB&&nA&&pB.arrAbs+TURN72>nA.depAbs)return;\n      /* 不能讓任何一架因為對調而在台北空等更久：對調後 B 的等待不可超過原本兩架較長的等待（至少容許 48 小時） */\n      if(pB&&nA){var oA928=nA.depAbs-r.arrAbs,oB928=y.depAbs-pB.arrAbs,nB928=nA.depAbs-pB.arrAbs;if(nB928>Math.max(oA928,oB928,2880))return}\n      if(!nA)return;if(!pB&&nA.depAbs>y.depAbs+1440)return;\n      var tA=LA.slice(ia+1),tB=LB.slice(iy);\n      /* 平均：對調後兩架的總班數都要在同機型平均 ±25 段以內 */\n      var cA=LA.length-tA.length+tB.length,cB=LB.length-tB.length+tA.length;\n      if(Math.abs(cA-avg928)>25||Math.abs(cB-avg928)>25)return;\n      dist[A]=LA.slice(0,ia+1).concat(tB);dist[B]=LB.slice(0,iy).concat(tA);\n      tB.forEach(function(q){owner.set(q,A)});tA.forEach(function(q){owner.set(q,B)});\n      n++;\n    });\n    window.KGM_SWAP_R928=window.KGM_SWAP_R928||{};window.KGM_SWAP_R928[type]={tried:tried,swapped:n};\n  }",1);
