/* 0928B · 審核中心「部門權限（可整個部門一次切換）」（使用者：「幫我分類然後確認每一頁都有在上面」）
   原本：28 列攤成一張表，沒有分類；「AI 對話查詢」「競標管理」沒寫在清單裡，是從側邊欄撿回來、排在最後；
   每列底下印的分頁代碼會被全站版號替換改成 cases0928B（跟實際的 cases0831B 對不起來，看起來像錯的）。
   現在：照左側選單的七個分類（航班營運／訂位與客服／會員服務／行銷／財務與航網／人資與組員／系統）分段，
   每段有一列「整個分類」可以對某部門一次切換；兩個漏掉的分頁放回「訂位與客服」；名稱跟左側選單一致；
   表頭上方即時比對左側選單，列出「左側 N 頁全部在表上」或缺了哪幾頁。
   順手修正：設成「可註解」的格子重畫後會顯示成「未解鎖」（下拉沒有 annot 這個選項），權限本身是對的，只是顯示錯。 */
RL("perm tabs","kgm-0903b-r123","  ['訂位與客服',[['bookings','定位管理'],['cases0831B','案件處理中心']]],/* 0913A：旅客資料更改併入案件處理中心 */\n  ['會員服務',[['members','會員管理'],['blacklist_r117','黑名單'],['milesverify','里程購買審核'],","  ['訂位與客服',[['bookings','定位管理'],['cases0831B','案件處理中心'],['cases0831C','AI 對話查詢'],['auctions','競標管理']]],/* 0913A：旅客資料更改併入案件處理中心；0928B：補上 AI 對話查詢、競標管理 */\n  ['會員服務',[['members','會員管理'],['blacklist_r117','黑名單'],['milesverify','里程購買審查'],",1);
RL("perm group setter","kgm-0903b-r123","window.kgmPermSetAcctR123=function(empId,tab,level){","/* 0928B：同一個分類一次切換 */\nwindow.kgmPermSetDeptGroupR928=function(dept,group,level){\n  if(!isCeo()){alert(z()?'只有執行長可以調整權限。':'CEO only.');return}\n  var p=P();p.dept[dept]=p.dept[dept]||{};\n  window.kgmPermTabsR123().filter(function(t){return t.group===group}).forEach(function(t){\n    if(level==='default')delete p.dept[dept][t.tab];else p.dept[dept][t.tab]=level});\n  try{save()}catch(_){}try{render()}catch(_){}\n};\nwindow.kgmPermSetAcctR123=function(empId,tab,level){",1);
RL("perm matrix","kgm-0903b-r123","  html+='<section class=\"k123-panel\"><header><small>PERMISSION MATRIX</small>'\n    +'<h3>'+(z()?'部門權限（可整個部門一次切換）':'Department permissions')+'</h3></header>'\n    +'<div class=\"k123-matrix\"><table class=\"k123-t\"><thead><tr><th>'+(z()?'分頁':'Page')+'</th>'","  /* 0928B：比對左側選單，確認每一頁都在表上 */\n  var cov928=(function(){try{var hasTab={},hasLab={};tabs.forEach(function(t){hasTab[t.tab]=1;hasLab[t.label]=1});var seen={},n=0,miss=[];\n    document.querySelectorAll('.p-admin-side button').forEach(function(b){\n      if(b.offsetParent===null||getComputedStyle(b).display==='none')return;   /* 隱藏的按鈕不算 */\n      var t=(b.textContent||'').trim(),m=/S\\.adminTab='([^']+)'/.exec(b.getAttribute('onclick')||'');\n      if(!t||/登出|Logout/.test(t))return;var key=m?m[1]:t;if(seen[key])return;seen[key]=1;n++;\n      if(!(m?hasTab[m[1]]:hasLab[t]))miss.push(t)});\n    return {n:n,miss:miss}}catch(_){return null}})();\n  /* 分類列用自己的下拉：各頁設定不一樣時顯示「各頁不同」，不會被當成未解鎖 */\n  var gsel928=function(cur,onch){var o=[['use',z()?'可使用':'Use'],['annot',z()?'可註解':'Annotate'],['none',z()?'未解鎖':'Locked']];\n    return '<select class=\"k928-gsel\" onchange=\"'+onch+'\">'+(cur?'':'<option value=\"\" selected disabled>'+(z()?'各頁不同':'Mixed')+'</option>')\n      +o.map(function(x){return '<option value=\"'+x[0]+'\"'+(cur===x[0]?' selected':'')+'>'+x[1]+'</option>'}).join('')+'</select>'};\n  var groups928=[];tabs.forEach(function(t){if(groups928.indexOf(t.group)<0)groups928.push(t.group)});\n  html+='<section class=\"k123-panel\"><header><small>PERMISSION MATRIX</small>'\n    +'<h3>'+(z()?'部門權限（可整個部門一次切換）':'Department permissions')+'</h3>'\n    +(cov928&&cov928.n?('<p class=\"k928-cov'+(cov928.miss.length?' bad':'')+'\">'+(cov928.miss.length\n      ?((z()?'左側選單有 ':'Sidebar has ')+cov928.n+(z()?' 頁，下表缺：':' pages; missing: ')+E(cov928.miss.join('、')))\n      :('✓ '+(z()?('左側選單 '+cov928.n+' 頁全部列在下表，共 '+groups928.length+' 個分類'):('All '+cov928.n+' sidebar pages listed in '+groups928.length+' groups'))))+'</p>'):'')\n    +'</header>'\n    +'<div class=\"k123-matrix\"><table class=\"k123-t\"><thead><tr><th>'+(z()?'分頁':'Page')+'</th>'",1);
RL("perm matrix body","kgm-0903b-r123","    +'</tr></thead><tbody>'\n    +tabs.map(function(t){\n      return '<tr><td>'+E(t.label)+'<br><small style=\"color:#9A948A\">'+E(t.tab)+'</small></td>'\n        +depts.map(function(d){\n          var cur=(p.dept[d]&&p.dept[d][t.tab])||'default';\n          return '<td>'+LEVELSEL(cur,\"kgmPermSetDeptR123('\"+d+\"','\"+t.tab+\"',this.value)\")+'</td>';\n        }).join('')+'</tr>';\n    }).join('')+'</tbody></table></div></section>';","    +'</tr></thead><tbody>'\n    +groups928.map(function(g){\n      var gt=tabs.filter(function(t){return t.group===g});\n      /* 0928B：分類標題列＋「整個分類」一次切換（全部同一個值時顯示那個值） */\n      return '<tr class=\"k928-grp\"><td><b>'+E(g)+'</b><small>'+gt.length+(z()?' 頁':' pages')+(z()?'　整個分類':' · whole group')+'</small></td>'\n        +depts.map(function(d){\n          var vals=gt.map(function(t){var v=(p.dept[d]&&p.dept[d][t.tab])||'none';return v==='view'?'annot':(v==='default'?'none':v)}),same=vals.every(function(v){return v===vals[0]});\n          return '<td>'+gsel928(same?vals[0]:'',\"kgmPermSetDeptGroupR928('\"+d+\"','\"+g+\"',this.value)\")+'</td>';\n        }).join('')+'</tr>'\n        +gt.map(function(t){\n          return '<tr class=\"k928-pg\"><td>'+E(t.label)+'</td>'\n            +depts.map(function(d){\n              var cur=(p.dept[d]&&p.dept[d][t.tab])||'default';\n              return '<td>'+LEVELSEL(cur,\"kgmPermSetDeptR123('\"+d+\"','\"+t.tab+\"',this.value)\")+'</td>';\n            }).join('')+'</tr>';\n        }).join('');\n    }).join('')+'</tbody></table></div></section>';",1);
RL("perm css","kgm-0903b-r123","+'.k123-empty{padding:22px;text-align:center;color:#9A948A;font-size:12px}';","+'.k123-empty{padding:22px;text-align:center;color:#9A948A;font-size:12px}'\n+'.k928-grp td{background:#F3F7F5;border-top:2px solid #D6E4DD}.k928-grp td:first-child b{display:block;color:#1F4E46;font-size:12.5px}'\n+'.k928-grp td:first-child small{display:block;color:#8A8578;font-size:10px;margin-top:2px}.k928-pg td:first-child{padding-left:26px}'\n+'.k928-cov{margin:6px 0 0;font-size:11.5px;color:#2E6B55}.k928-cov.bad{color:#B04A38;font-weight:700}'\n+'.k123-matrix thead th{position:sticky;top:0;z-index:1}'\n+'.k928-gsel{font-size:11.5px;padding:4px 8px;border:1px solid #9FBFB2;border-radius:8px;background:#fff;font-weight:700;color:#1F4E46}';",1);
RL("perm levelsel annot","kgm-0903b-r123","  var unset=(!cur||cur==='default');\n  return '<select class=\"k123-sel","  if(cur==='annot')cur='view';   /* 0928B：存的是 annot（r197），這裡沒有 annot 選項 → 以前一律顯示成未解鎖 */\n  var unset=(!cur||cur==='default');\n  return '<select class=\"k123-sel",1);
RL("perm whole dept row","kgm-0903b-r123","      return '<td>'+LEVELSEL('',\"kgmPermSetDeptAllR123('\"+d+\"',this.value)\")+'</td>'}).join('')","      var va928=tabs.map(function(t){var v=(p.dept[d]&&p.dept[d][t.tab])||'none';return v==='view'?'annot':(v==='default'?'none':v)}),sa928=va928.every(function(v){return v===va928[0]});   /* 0928B：不一樣就寫「各頁不同」 */\n      return '<td>'+gsel928(sa928?va928[0]:'',\"kgmPermSetDeptAllR123('\"+d+\"',this.value)\")+'</td>'}).join('')",1);
