/* 0928B · 選位圖：嬰兒同行的座位標上小孩圖示（使用者：「選位如果是嬰兒的話請用小孩標記在那個位置上（告知其他旅客）」）
   · 其他旅客：已被選走的座位裡，帶嬰兒的那一位（真實訂位看 paxList 裡的 INF；模擬旅客約 2% 帶嬰兒，決定性）標 👶。
   · 自己：這筆訂位有嬰兒時，自己選的座位（前 N 個，N＝嬰兒數）也標 👶，讓你知道別人看得到。
   訂位流程選位（.seat）與行程管理選位（.mt-seat0814）兩張座位圖都套用；畫面重畫後自動補上，圖例加一格。 */
RL('infant seat marker','kgm-0909E-r229',
"try{console.log('KGM '+BUILD+' r229 loaded')}catch(_){}\n})();",
"/* ══ 0928B：選位圖 · 嬰兒同行座位 ══════════════════════════════════ */\n"
+"(function(){\n"
+"  function Zi(){try{return LANG!=='en'}catch(_){return true}}\n"
+"  function hs(k){var h=2166136261;k=String(k);for(var i=0;i<k.length;i++){h^=k.charCodeAt(i);h=(h*16777619)>>>0}return h>>>0}\n"
+"  function infN(list){return (list||[]).filter(function(p){return p&&(p.passengerType==='INF'||p.type==='INF')}).length}\n"
+"  function segsOf(b){try{return (typeof window.segs7==='function'?window.segs7(b):[])||[]}catch(_){return []}}\n"
+"  /* 同一班、同一天：哪些座位有嬰兒同行（真實訂位）＋哪些座位被真實訂位佔用 */\n"
+"  function realMap(f,date){\n"
+"    var inf={},occ={};\n"
+"    (S.bookings||[]).forEach(function(b){\n"
+"      if(!b||b.status==='cancelled')return;var n=infN(b.paxList);\n"
+"      segsOf(b).forEach(function(s){\n"
+"        if(!s||!s.f||s.f.code!==f.code||s.f.fr!==f.fr||s.f.to!==f.to||s.date!==date)return;\n"
+"        var seats=Object.keys((b.seats&&b.seats[s.key])||{}).filter(function(x){return x!=='_auto'});\n"
+"        seats.forEach(function(x){occ[x]=1});seats.slice(0,n).forEach(function(x){inf[x]=1});\n"
+"      });\n"
+"    });\n"
+"    return {inf:inf,occ:occ};\n"
+"  }\n"
+"  window.kgmInfantSeatsR928=realMap;\n"
+"  function mark(el,own){\n"
+"    if(el.classList.contains('k928-inf'))return;\n"
+"    el.classList.add('k928-inf');if(own)el.classList.add('k928-inf-own');\n"
+"    var t=el.getAttribute('title')||'';el.setAttribute('title',t+(Zi()?' · 嬰兒同行':' · travelling with an infant'));\n"
+"    if(!el.style.position)el.style.position='relative';\n"
+"    var i=document.createElement('i');i.className='k928-inf-i';i.setAttribute('aria-hidden','true');i.textContent='\\uD83D\\uDC76';el.appendChild(i);\n"
+"  }\n"
+"  function legend(host){\n"
+"    if(!host||host.querySelector('.k928-inf-lg'))return;\n"
+"    var d=document.createElement('div');d.className='k928-inf-lg';\n"
+"    d.innerHTML='<span class=\"k928-inf-i\">\\uD83D\\uDC76</span>'+(Zi()?'嬰兒同行座位（其他旅客選位時看得到）':'Passenger travelling with an infant');\n"
+"    host.appendChild(d);\n"
+"  }\n"
+"  function doFlight(els,f,date,ownInf,ownSel){\n"
+"    if(!f||!date||!els.length)return;\n"
+"    var R=realMap(f,date),first=[];\n"
+"    els.forEach(function(e){\n"
+"      var sid=e.sid;\n"
+"      if(e.own){if(ownInf>0)first.push(e);return}\n"
+"      if(!e.taken)return;\n"
+"      if(R.inf[sid]||(!R.occ[sid]&&!e.front&&(hs('INF|'+f.code+'|'+date+'|'+sid)%100)<2))mark(e.el,false);\n"
+"    });\n"
+"    first.slice(0,ownInf).forEach(function(e){mark(e.el,true)});\n"
+"  }\n"
+"  function run(){\n"
+"    try{\n"
+"      var app=document.getElementById('app');if(!app)return;\n"
+"      /* 訂位流程 */\n"
+"      var fl=[].slice.call(app.querySelectorAll('.seat[onclick^=\"toggleSeat(\"]'));\n"
+"      if(fl.length){\n"
+"        var byKey={};\n"
+"        fl.forEach(function(el){var m=/toggleSeat\\('([^']+)','([^']+)'/.exec(el.getAttribute('onclick')||'');if(!m)return;\n"
+"          (byKey[m[1]]=byKey[m[1]]||[]).push({el:el,sid:m[2],taken:el.classList.contains('lk'),own:el.classList.contains('sel'),front:el.classList.contains('f')||el.classList.contains('k65-res')})});\n"
+"        Object.keys(byKey).forEach(function(k){\n"
+"          var f=k==='out'?S.outF:(k==='inb'?S.inbF:null);if(!f)return;\n"
+"          var date=f.date||(k==='out'?(S.search||{}).dep:(S.search||{}).ret);\n"
+"          doFlight(byKey[k],f,date,infN(S.paxList));\n"
+"        });\n"
+"        var lg=[].slice.call(app.querySelectorAll('b')).filter(function(b){return /^(圖例|Legend)$/.test(String(b.textContent||'').trim())})[0];\n"
+"        if(lg&&app.querySelector('.k928-inf'))legend(lg.parentNode);\n"
+"      }\n"
+"      /* 行程管理 */\n"
+"      var mt=[].slice.call(app.querySelectorAll('.mt-seat0814[onclick^=\"bkToggleSeat(\"]'));\n"
+"      if(mt.length){\n"
+"        var g={};\n"
+"        mt.forEach(function(el){var m=/bkToggleSeat\\('([^']+)','([^']+)','([^']+)'/.exec(el.getAttribute('onclick')||'');if(!m)return;\n"
+"          (g[m[1]+'|'+m[2]]=g[m[1]+'|'+m[2]]||[]).push({el:el,sid:m[3],taken:el.classList.contains('taken'),own:el.classList.contains('on')})});\n"
+"        Object.keys(g).forEach(function(k){\n"
+"          var p=k.split('|'),b=(S.bookings||[]).filter(function(x){return x&&x.pnr===p[0]})[0];if(!b)return;\n"
+"          var s=segsOf(b).filter(function(x){return x.key===p[1]})[0];if(!s)return;\n"
+"          doFlight(g[k],s.f,s.date,infN(b.paxList));\n"
+"        });\n"
+"        var card=app.querySelector('.mt-seat-card0814');if(card&&app.querySelector('.k928-inf'))legend(card);\n"
+"      }\n"
+"    }catch(e){try{console.warn('0928B infant seats',e)}catch(_){}}\n"
+"  }\n"
+"  window.kgmInfantSeatSweepR928=run;\n"
+"  if(!document.getElementById('kgm-928-inf-css')){\n"
+"    var st=document.createElement('style');st.id='kgm-928-inf-css';\n"
+"    st.textContent='.k928-inf-i{position:absolute;top:-7px;right:-7px;font-size:11px;line-height:1;font-style:normal;'\n"
+"      +'background:#fff;border:1px solid #e3d6b4;border-radius:999px;padding:1px 2px;box-shadow:0 1px 3px rgba(0,0,0,.12);pointer-events:none;z-index:2}'\n"
+"      +'.k928-inf-own .k928-inf-i{border-color:#c9a661;background:#fff8e6}'\n"
+"      +'.k928-inf-lg{display:flex;align-items:center;gap:6px;margin-top:6px;font-size:11px;color:#5b6570}'\n"
+"      +'.k928-inf-lg .k928-inf-i{position:static;display:inline-block}';\n"
+"    (document.head||document.documentElement).appendChild(st);\n"
+"  }\n"
+"  var RAF=0;\n"
+"  function hook(){\n"
+"    var app=document.getElementById('app');if(!app)return false;if(app.__k928inf)return true;app.__k928inf=1;\n"
+"    new MutationObserver(function(){if(RAF)return;RAF=requestAnimationFrame(function(){RAF=0;run()})}).observe(app,{childList:true,subtree:true});\n"
+"    run();return true;\n"
+"  }\n"
+"  if(!hook())document.addEventListener('DOMContentLoaded',hook);\n"
+"})();\n"
+"try{console.log('KGM '+BUILD+' r229 loaded')}catch(_){}\n})();",1);
