/* 0928B · 旅客自己改票的艙等（使用者：「用戶端改票如果是購買經濟艙要顯示豪經艙如果經濟艙沒有，就如果前一個沒有就顯示往上一個Level的，
   但是豪經不會顯示經濟的（除了A21X的神戶航班例外）」）
   原本：改票只在原艙等裡找（nextSellableFareForChange 只沿同艙票種往上），新航班的機型沒有這個艙等或已售完，
   就只寫「此機型無此艙等／無可售訂位艙等」，旅客改不了。另外判斷機型用的是時刻表上的機型，不是那一天實際派的機型。
   現在：原艙等可以就用原艙等；不行 → 依序往上一級找（經濟→豪經→商務→頭等），用同一個票價家族（基本／超值／豪華），差額照實收。
   永遠不往下降艙；唯一例外是神戶航班（UKB）：A21N 沒有豪經艙，豪經旅客可以改到經濟艙。
   付款視窗與結果都列出「艙等 A → B」。 */
R("rebook helper","function changeQuote(pnr,seg,newDate,flCode,fr,to){\n  var bk=(S.bookings||[]).find(function(b){return b.pnr===pnr;});","/* 0928B：原艙等在新航班不能用時，往上一級找可售艙等；神戶航班豪經可改經濟 */\nvar KGM_CAB_ZH_R928={Economy:'經濟艙',Premium:'豪華經濟艙',Business:'商務艙',First:'頭等艙',Resident:'Residence'};\nfunction kgmChangeCabinR928(newF,newDate,fc,pax,sell){\n  if(!newF)return null;\n  var ORDER=['Economy','Premium','Business','First'],MAP={Economy:'econ',Premium:'prem',Business:'biz',First:'suite'};\n  var fare=FARES[fc]||AWARD_FARES[fc]||{},cab=fare.cabin||'Economy',fam=fare.familyR48||fare.family||'';\n  var i0=ORDER.indexOf(cab);if(i0<0)return null;\n  var ak='';try{ak=(typeof acftOfFlight==='function'&&acftOfFlight(newF.code,newDate))||newF.acft}catch(_){ak=newF.acft}\n  var ac=AC[ak]||{},has=function(c){return !!(ac.cabins&&ac.cabins[MAP[c]])};\n  if(has(cab)&&sell&&!sell.full)return null;\n  /* 先在原艙等往上一個票價家族找（基本→超值→豪華）；整個艙等都沒有，才往上一級艙等 */\n  var RANK={Basic:0,Value:1,Deluxe:2},r0=RANK[fam]||0,tries=[cab];\n  if(cab==='Premium'&&(newF.fr==='UKB'||newF.to==='UKB')&&!has('Premium'))tries.push('Economy');\n  for(var i=i0+1;i<ORDER.length;i++)tries.push(ORDER[i]);\n  var valid=[];try{valid=validCodes(Object.assign({},newF,{date:newDate}))||[]}catch(_){}\n  var famOf=function(x){return (FARES[x]||{}).familyR48||(FARES[x]||{}).family||''};\n  for(var k=0;k<tries.length;k++){\n    var c=tries[k];if(!has(c))continue;\n    var codes=valid.filter(function(x){return (FARES[x]||{}).cabin===c&&x!==fc&&(c!==cab||(RANK[famOf(x)]||0)>=r0)});if(!codes.length)continue;\n    codes.sort(function(a,b){var fa=famOf(a)===fam?-1:(RANK[famOf(a)]||0),fb=famOf(b)===fam?-1:(RANK[famOf(b)]||0);return fa-fb});\n    for(var j=0;j<codes.length;j++){\n      var s2=nextSellableFareForChange(newF,newDate,codes[j],pax);\n      if(s2&&!s2.full)return {sell:s2,code:s2.code,cabin:c,dir:c===cab?0:(ORDER.indexOf(c)>i0?1:-1)};\n    }\n  }\n  return null;\n}\nfunction changeQuote(pnr,seg,newDate,flCode,fr,to){\n  var bk=(S.bookings||[]).find(function(b){return b.pnr===pnr;});",1);
R("rebook quote use","  var sell=nextSellableFareForChange(newF,newDate,fc,pax);\n  var newFc=sell.code,seatsLeft=sell.left;","  var sell=nextSellableFareForChange(newF,newDate,fc,pax);\n  var newFc=sell.code,seatsLeft=sell.left;\n  var cab0=(FARES[fc]&&FARES[fc].cabin)||(AWARD_FARES[fc]&&AWARD_FARES[fc].cabin)||\"Economy\",newCab=cab0,cabMove=0;\n  try{var up928=kgmChangeCabinR928(newF,newDate,fc,pax,sell);if(up928){sell=up928.sell;newFc=up928.code;seatsLeft=sell.left;newCab=up928.cabin;cabMove=up928.dir;}}catch(_){}   /* 0928B */",1);
R("rebook quote return","    oldP:oldP,newP:newP,curr:bk.curr||\"TWD\",seatsLeft:seatsLeft,full:full};","    oldP:oldP,newP:newP,curr:bk.curr||\"TWD\",seatsLeft:seatsLeft,full:full,cabin0:cab0,newCabin:newCab,cabinMove:cabMove};",1);
R("rebook pending cabin","    fee:q.fee,diff:q.diff,saved:q.saved,total:q.total,curr:q.curr,oldFc:q.fc,newFc:q.newFc};\n  S.modal={type:\"changePay\",data:{pnr:pnr}};","    fee:q.fee,diff:q.diff,saved:q.saved,total:q.total,curr:q.curr,oldFc:q.fc,newFc:q.newFc,oldCabin:q.cabin0,newCabin:q.newCabin};\n  S.modal={type:\"changePay\",data:{pnr:pnr}};",1);
R("rebook check cabin","  var acData=AC[nf.acft]||AC.B789;\n  var cabinMap={Economy:\"econ\",Premium:\"prem\",Business:\"biz\",First:\"suite\"};\n  var hasCabin=!!(acData.cabins&&acData.cabins[cabinMap[cabin]]);","  var acData=AC[(function(){try{return acftOfFlight(nf.code,d)}catch(_){return ''}})()||nf.acft]||AC[nf.acft]||AC.B789;   /* 0928B：看當天實際派的機型 */\n  var cabinMap={Economy:\"econ\",Premium:\"prem\",Business:\"biz\",First:\"suite\"};\n  var hasCabin=!!(acData.cabins&&acData.cabins[cabinMap[cabin]]);\n  var q928=null;try{q928=changeQuote(pnr,seg,d,code,fr,to)}catch(_){}\n  var mv928=q928&&q928.newCabin&&q928.newCabin!==cabin&&!q928.full,noCab928=!hasCabin;if(mv928)hasCabin=true;\n  var cz928=function(c){return LANG===\"en\"?c:(KGM_CAB_ZH_R928[c]||c)};",1);
R("rebook check cabin line","      +'<div style=\"font-size:12px;margin-top:2px\">'+(LANG===\"en\"?\"Cabin\":\"艙等\")+': '+cabin+' — '+(hasCabin?","      +(mv928?'<div style=\"font-size:12px;margin-top:2px\">'+(LANG===\"en\"?\"Cabin\":\"艙等\")+': <b>'+cz928(cabin)+' → '+cz928(q928.newCabin)+'</b></div><div style=\"font-size:11px;color:#8c5f13;margin-top:2px\">'+(LANG===\"en\"?((noCab928?(\"This day's aircraft has no \"+cabin+\" cabin\"):(cabin+\" is sold out on this flight\"))+\", so \"+(q928.cabinMove>0?\"the next cabin up\":q928.newCabin)+\" is offered; the fare difference is shown below.\"):((noCab928?('這一天的機型沒有'+cz928(cabin)):(cz928(cabin)+'在這個航班已售完'))+'，改提供'+(q928.cabinMove>0?'上一級的':'')+cz928(q928.newCabin)+'，票價差額列在下方。'))+'</div>':'<div style=\"font-size:12px;margin-top:2px\">'+(LANG===\"en\"?\"Cabin\":\"艙等\")+': '+cz928(cabin)+' — '+(hasCabin?",1);
R("rebook check cabin line end","(LANG===\"en\"?\"cabin not on this aircraft\":\"此機型無此艙等\")+'</span>'))+'</div>'","(LANG===\"en\"?\"cabin not available on this flight\":\"此航班沒有可改的艙等\")+'</span>'))+'</div>')",1);
R("rebook pay cabin","      <div style=\"display:flex;justify-content:space-between\"><span>${LANG===\"en\"?\"Booking class\":\"訂位艙等\"}</span><span><b>${pc.oldFc||\"—\"}</b> → <b>${pc.newFc||pc.oldFc||\"—\"}</b></span></div>","      ${pc.newCabin&&pc.oldCabin&&pc.newCabin!==pc.oldCabin?`<div style=\"display:flex;justify-content:space-between\"><span>${LANG===\"en\"?\"Cabin\":\"艙等\"}</span><span><b>${LANG===\"en\"?pc.oldCabin:(KGM_CAB_ZH_R928[pc.oldCabin]||pc.oldCabin)}</b> → <b>${LANG===\"en\"?pc.newCabin:(KGM_CAB_ZH_R928[pc.newCabin]||pc.newCabin)}</b></span></div>`:\"\"}\n      <div style=\"display:flex;justify-content:space-between\"><span>${LANG===\"en\"?\"Booking class\":\"訂位艙等\"}</span><span><b>${pc.oldFc||\"—\"}</b> → <b>${pc.newFc||pc.oldFc||\"—\"}</b></span></div>",1);
R("card changePay","    <label style=\"font-size:11px;color:var(--sub);display:block;margin-bottom:2px\">${LANG===\"en\"?\"Card Number\":\"卡號\"}</label>\n    <input id=\"ccNum\" class=\"inp\" style=\"height:34px;margin-bottom:8px\" placeholder=\"4242 4242 4242 4242\" maxlength=\"19\">\n    <div style=\"display:flex;gap:8px;margin-bottom:8px\">\n      <div style=\"flex:1\"><label style=\"font-size:11px;color:var(--sub);display:block;margin-bottom:2px\">${LANG===\"en\"?\"Expiry\":\"到期\"}</label><input id=\"ccExp\" class=\"inp\" style=\"height:34px\" placeholder=\"MM/YY\" maxlength=\"5\"></div>\n      <div style=\"flex:1\"><label style=\"font-size:11px;color:var(--sub);display:block;margin-bottom:2px\">CVV</label><input id=\"ccCvv\" class=\"inp\" style=\"height:34px\" placeholder=\"123\" maxlength=\"4\"></div>\n    </div>\n    <label style=\"font-size:11px;color:var(--sub);display:block;margin-bottom:2px\">${LANG===\"en\"?\"Cardholder Name\":\"持卡人姓名\"}</label>\n    <input id=\"ccName\" class=\"inp\" style=\"height:34px;margin-bottom:14px\" placeholder=\"${LANG===\"en\"?\"Name on card\":\"卡片姓名\"}\">","    <style>.modal-box:has(.k928-chgpay){max-width:900px!important;width:min(900px,94vw)!important;max-height:92vh;overflow:auto}.k928-chgpay{margin-bottom:14px}</style>\n    <div class=\"k928-chgpay\">${kgmCardFormR923({key:'chg',ids:{num:'ccNum',name:'ccName',expM:'ccExpM',expY:'ccExpY',exp:'ccExp',cvv:'ccCvv'},contact:false,ssl:(LANG===\"en\"?\"256-bit encrypted. Your card is charged only when you press the button below.\":\"256-bit 加密傳輸。按下方「付款並確認改票」後才會扣款。\")})}</div>",1);
