/* 0927B · 報到櫃檯：每個櫃檯 2–3 班；不再規定每個時段要開幾個櫃檯 */
RL('r116 no forced split','kgm-0903b-r116',
"  flush();\n  /* 最少要開得出兩櫃：兩班以上就不要全部擠在同一櫃 */\n  if(out.length===1&&out[0].length>=2){\n    var a=out[0],half=Math.ceil(a.length/2);\n    out=[a.slice(0,half),a.slice(half)];\n  }\n  /* 四班以上至少三櫃 */\n  if(out.length===2&&(out[0].length+out[1].length)>=4){\n    var flat=out[0].concat(out[1]),n=Math.ceil(flat.length/3),g=[],k;\n    for(k=0;k<flat.length;k+=n)g.push(flat.slice(k,k+n));\n    if(g.length>=3)out=g;\n  }\n  return out.filter(function(x){return x.length});",
"  flush();\n  /* 0927B：使用者：「是每個櫃檯至少兩到三個航班，沒有規定每個時段幾個櫃檯」。\n     原本這裡硬把兩班拆成兩櫃、四班以上拆成三櫃，反而做出「一櫃一班」。\n     改成：不再強迫多開櫃；只剩一班的櫃，併進前一櫃或後一櫃；兩邊都已經 3 班就向鄰櫃借一班變 2＋2\n     （一櫃上限 3 班；有 A388 的櫃上限 2 班、而且不能兩班 A388 —— 這條規則不變）。 */\n  function canTake927(g,f){\n    var hasBig=g.some(isA388),cap=hasBig?window.KGM_COUNTER_MAX_A388_R116:window.KGM_COUNTER_MAX_R116;\n    if(isA388(f)){if(hasBig)return false;cap=window.KGM_COUNTER_MAX_A388_R116}\n    return g.length<cap;\n  }\n  for(var s927=0;s927<out.length;s927++){\n    if(out.length<2||out[s927].length!==1)continue;\n    var one=out[s927][0],to927=-1;\n    if(s927>0&&canTake927(out[s927-1],one))to927=s927-1;\n    else if(s927+1<out.length&&canTake927(out[s927+1],one))to927=s927+1;\n    if(to927<0){\n      /* 兩邊都滿（3 班）：向鄰櫃借一班，變成 2＋2（A388 規則照樣檢查） */\n      var nb=[];for(var j0=0;j0<out.length;j0++)if(j0!==s927&&out[j0].length>=3)nb.push(j0);\n      nb.sort(function(a,b){return Math.abs(a-s927)-Math.abs(b-s927)});   /* 先借最近的一櫃 */\n      for(var q927=0;q927<nb.length;q927++){\n        var j=nb[q927],order=j<s927?out[j].slice().reverse():out[j].slice(),cand=null;\n        for(var c927=0;c927<order.length;c927++){if(canTake927(out[s927],order[c927])){cand=order[c927];break}}\n        if(!cand)continue;\n        out[j].splice(out[j].indexOf(cand),1);\n        if(j<s927)out[s927].unshift(cand);else out[s927].push(cand);\n        break;\n      }\n      continue;\n    }\n    if(to927<s927)out[to927].push(one);else out[to927].unshift(one);\n    out.splice(s927,1);s927--;\n  }\n  return out.filter(function(x){return x.length});");
RL('r116 header','kgm-0903b-r116',"     · 地勤一天八小時，每個時段至少要開得出 2–3 個櫃檯，不能全部擠在一櫃。\n",
 "     · 地勤一天八小時，每個時段至少要開得出 2–3 個櫃檯，不能全部擠在一櫃。\n       （0927B：使用者更正 —— 沒有規定每個時段幾個櫃檯，規則是每個櫃檯 2–3 班。）\n");
/* 同一時段同一航廈，櫃號不可以重複 —— 重複就等於一個櫃檯同時做兩組、超過 3 班 */
RL('r116 unique counter no','kgm-0903b-r116',"          while(cs.length<groups.length)cs.push(String(cs.length+1));",
 "          /* 0927B：原本補櫃號是 String(cs.length+1)，會撞到已經在用的號碼（同一時段出現兩個 6 號櫃），\n             等於一個櫃檯同時負責兩組、超過 3 班。改成先從這一站這一航廈真的有的櫃號挑沒用過的，沒有才往後找空號。 */\n          while(cs.length<groups.length){\n            var pool927=[];try{pool927=(typeof _countersFor==='function'?_countersFor(ap,t):[])||[]}catch(_){}\n            var nx927=pool927.map(String).filter(function(c){return cs.indexOf(c)<0})[0];\n            if(nx927==null){var n927=1;while(cs.indexOf(String(n927))>=0)n927++;nx927=String(n927)}\n            cs.push(nx927);\n          }");
