/* 0927B · 機隊：B779 重疊的根本原因（日光節約時區的落地時間） */
RL('durOn72','kgm-0823o-r72',"function durOf72(f){\n  var d=+f.dur||0;\n  if(!d){try{d=blockMin(f.fr,f.to,f.dep,f.arr,f.dd||0)||0}catch(_){}}\n  if(!d||d<25)d=120;\n  return d;\n}",
"function durOf72(f){\n  var d=+f.dur||0;\n  if(!d){try{d=blockMin(f.fr,f.to,f.dep,f.arr,f.dd||0)||0}catch(_){}}\n  if(!d||d<25)d=120;\n  return d;\n}\n/* 0927B：B779 縮到 40 架出現「KX55 還沒落地 KX288 就起飛」的根本原因。\n   排班一直用「起飛絕對時間（依當地日光節約換算）＋表定 dur」推落地時間。\n   日光節約期間（例：奧克蘭 NZDT 2026-09-27～2027-04-04）起飛的絕對時間早一小時，\n   dur 卻沒跟著變，推出來的落地比時刻表早一小時：KX55 AKL 17:25→TPE 23:40 實際 675 分，\n   排班當成 615 分、22:40 落地，55 分鐘過站後就把 23:35 的 KX288 接上去。\n   稽核與畫面用的是時刻表的抵達時間（23:40），所以才抓到重疊。\n   改成：有日期就用時刻表的起飛、抵達各自換算成絕對時間相減；算不出來才用 dur。 */\nfunction durOn72(f,date){\n  var d0=durOf72(f);\n  if(!f||!date||f.positioningR830)return d0;\n  try{\n    var a=_fUTC(f,date,'dep'),b=_fUTC(f,date,'arr'),d=b-a;\n    if(isFinite(d)&&d>=25&&d<=2*1440)return d;\n  }catch(_){}\n  return d0;\n}\nwindow.kgmDurOnR927=durOn72;");
RL('dur build','kgm-0823o-r72',"var x={f:f,date:date,di:di,depAbs:depAbs,arrAbs:depAbs+durOf72(f),u:0};","var x={f:f,date:date,di:di,depAbs:depAbs,arrAbs:depAbs+durOn72(f,date),u:0};");
RL('dur second','kgm-0823o-r72',"      arrAbs:secDep+durOf72(sec),u:0,synthR72:1});","      arrAbs:secDep+durOn72(sec,D(w0,x.di+secK)),u:0,synthR72:1});");
RL('dur initTail','kgm-0823o-r72',"f=flight72(q.code,fr,to,q.date);return [dep,dep+(q.positioningR830?ferryDur72(fr,to):f?durOf72(f):180)","f=flight72(q.code,fr,to,q.date);return [dep,dep+(q.positioningR830?ferryDur72(fr,to):f?durOn72(f,q.date):180)");
RL('dur expected','kgm-0823o-r72',"arrAbs:epoch72(date,f.dep,f.fr)+durOf72(f),u:false});","arrAbs:epoch72(date,f.dep,f.fr)+durOn72(f,date),u:false});");
RL('dur span','kgm-0823o-r72',"rowEpoch72(z)+((z.positioningR830)?ferryDur72(z.fr,z.to):durOf72(z._f||z))]}","rowEpoch72(z)+((z.positioningR830)?ferryDur72(z.fr,z.to):durOn72(z._f||z,z.date))]}");
RL('dur continuity','kgm-0823o-r72',"var dur=x.positioningR830?ferryDur72(fr,to):(f?durOf72(f):Math.max(60,ferryDur72(fr,to)));","var dur=x.positioningR830?ferryDur72(fr,to):(f?durOn72(f,x.date):Math.max(60,ferryDur72(fr,to)));");

/* ── 0927B · B78X：松山回桃園照常飛桃園班 —— 松山派駐只留一份計畫 ── */
RL('r148 follow seedTsa72','kgm-0907a-r148',"window.kgmTsaRotateR148=function(force){\n  var out={tours:[],swaps:0,groups:0,skipped:null,tour:+window.KGM_TSA_TOUR_R148||62};\n  var TA=null;try{TA=S.tailAssign}catch(_){}\n  if(!TA){out.skipped='no-tailAssign';return out}",
"window.kgmTsaRotateR148=function(force){\n  var out={tours:[],swaps:0,groups:0,skipped:null,tour:+window.KGM_TSA_TOUR_R148||62};\n  var TA=null;try{TA=S.tailAssign}catch(_){}\n  if(!TA){out.skipped='no-tailAssign';return out}\n  /* 0927B：0913B 起，松山派駐由 r72 的 seedTsa72 依使用者逐字規格排定（S.tsaWindowsR913：\n     同時 3 架、A／B 約兩個月、C 約一個月、離開後至少 183 天）。r72 排一般班時就是避開這些區間。\n     這一層是 0907A 的舊規則（4 架一組、62 天整段對調），它在 90／120 秒後再對調一次，\n     松山勤務就被搬到別架：原本派駐的那架「區間被擋住、卻沒有松山班」，\n     真正飛松山的那架「離開松山之後一段桃園班都沒有」—— 這就是 B78X 長時間空白的原因。\n     有逐字規格的計畫時就只照計畫畫輪替表、不再對調。 */\n  var W927=null;try{W927=S.tsaWindowsR913}catch(_){}\n  if(W927&&Object.keys(W927).length){\n    var list927=[];Object.keys(W927).forEach(function(t){(W927[t]||[]).forEach(function(w){if(w&&w.in)list927.push({t:t,in:w.in,out:w.out||w.in})})});\n    list927.sort(function(a,b){return a.in.localeCompare(b.in)||a.t.localeCompare(b.t)});\n    out.tours=list927.map(function(w,i){return {tour:i+1,from:w.in,to:w.out,group:0,target:[w.t],before:[w.t],after:[w.t],swapDate:null,swapped:0,planR927:true}});\n    out.groups=1;out.planR927=true;out.skipped='plan-913';\n    var today927=T(),now927={};list927.forEach(function(w){if(today927>=w.in&&today927<=w.out)now927[w.t]=1});\n    if(Object.keys(now927).length)S.tsaFleet=now927;\n    out.today=Object.keys(now927);\n    window.KGM_TSA_R148=out;\n    return out;\n  }");
RL('r148 paint text','kgm-0907a-r148',"    +'<p class=\"sub\">'+(z()\n      ?('16 架 B78X 分 '",
"    +'<p class=\"sub\">'+(r.planR927?(z()\n      ?'依松山派駐規則：同時駐 3 架 B78X（A／B 兩架每天對調、各待約兩個月；C 一架約一個月），以實體航班交接；離開松山後至少 183 天才會再派駐，回到桃園照常飛桃園班表。'\n      :'Songshan posting rules: three B78X at TSA (A/B swap daily, about two months each; C about one month), exchanged on real flights; at least 183 days before a tail returns, and it flies normal Taoyuan schedules in between.'):(z()\n      ?('16 架 B78X 分 '");
RL('r148 paint text end','kgm-0907a-r148',"        +'cannot be posted to TSA again for '+((r.groups-1)*tour)+' days (≥'+window.KGM_TSA_GAP_MIN_R148+' days / six months).'))\n    +'</p>",
"        +'cannot be posted to TSA again for '+((r.groups-1)*tour)+' days (≥'+window.KGM_TSA_GAP_MIN_R148+' days / six months).')))\n    +'</p>");
RL('r148 tour label','kgm-0907a-r148',"        +'<b>'+(z()?'第 ':'Tour ')+(x.tour)+(z()?' 梯 · 第 ':' · group ')+(x.group+1)+(z()?' 組':'')+'</b>'",
"        +'<b>'+(z()?'第 ':'Tour ')+(x.tour)+(x.planR927?(z()?' 梯':''):((z()?' 梯 · 第 ':' · group ')+(x.group+1)+(z()?' 組':'')))+'</b>'");
RL('r72 live incl tsa','kgm-0823o-r72',"  var live=tails.filter(function(t){return !mxSet[t]&&!((S.tsaFleet||{})[t])&&!RESERVE_TYPE72[t]});",
"  /* 0927B：原本把「排班起始日正在松山」的那 3 架整年排除在一般班之外，所以它們一離開松山就整段空白。\n     使用者：「TSA 排班回 TPE 要排 TPE 的航班正常執行 TPE 的飛行」。松山派駐期間由 tsaBusy72() 逐日擋，\n     這裡不再整年排除。 */\n  var live=tails.filter(function(t){return !mxSet[t]&&!RESERVE_TYPE72[t]});");
RL('r72 fresh tsa busy','kgm-0823o-r72',"        if((frS==='TPE'||x.di<WARM72)&&(!fresh||pos[fresh].n>st.n))fresh=tl;\n        continue;",
"        if(tsaBusy72(tl,x.date))continue;          /* 0927B：駐松山期間不接一般班表（新投入的機身也一樣） */\n        if((frS==='TPE'||x.di<WARM72)&&(!fresh||pos[fresh].n>st.n))fresh=tl;\n        continue;");
RL('r72 recovery incl tsa','kgm-0823o-r72',"    try{tails=(tailsFor(type)||[]).filter(function(t){return !((S.tsaFleet||{})[t])})}catch(_){}",
"    /* 0927B：松山派駐期間由 canFit→unavailable72→tsaBusy72 逐日擋；起始日在松山的那幾架離開後也要能補班 */\n    try{tails=(tailsFor(type)||[]).slice()}catch(_){}");
/* ── 0927B · B789／B78X 長時間空白：外站等超過 6 天就先調機回台北 ── */
RL('r72 split long outstation waits','kgm-0823o-r72',"  blocks=blocks.concat(rescueBlocks);\n",
"  blocks=blocks.concat(rescueBlocks);\n  /* 0927B：B789 在多倫多等 8～10 天、B78X 停在沖繩一整個月的原因。\n     第一輪排班「外站只能由剛飛對號去程的同一架接回」，而時刻表本身進出不平衡\n     （例：60 天內 B789 飛進 YYZ 99 班、飛出的營收班只有 77 班），多出來的飛機只能排隊，\n     於是一個勤務裡夾著一段好幾天的外站空等，那架飛機整段時間都不能飛別的班。\n     這裡把「外站地面等待超過 6 天」的勤務在等待處切開（門檻 KGM_SPLIT_WAIT_H_R927＝144 小時；\n     設 72 小時可以把空白壓到 0，但一年要多飛約 1,600 段空機長程調機，不合理）：落地後先調機回台北，\n     下一段起飛前再調機過去。兩半都是台北進出的封閉勤務，交給下面的月平均分派；\n     營收航段一段都不動、也不拆第五航權（中停只停一兩個小時，不會被切）。 */\n  (function(){\n    var base927=Math.floor(Date.parse(w0+'T00:00:00Z')/60000),LIM927=(+window.KGM_SPLIT_WAIT_H_R927||144)*60,sq927=40,out927=[],n927=0;\n    blocks.forEach(function(b){\n      var cur=[];\n      for(var i=0;i<b.length;i++){\n        var x=b[i],nx=b[i+1];cur.push(x);\n        if(!nx)break;\n        var st=sta(x.to||String(x.route||'').split('→')[1]);\n        if(!st||st==='TPE'||st==='TSA')continue;\n        if(x.positioningR830||nx.positioningR830)continue;\n        if(!(isFinite(+x.arrAbs)&&isFinite(+nx.depAbs))||(+nx.depAbs)-(+x.arrAbs)<=LIM927)continue;\n        var dH=ferryDur72(st,'TPE'),dB=ferryDur72('TPE',st);\n        var hDep=(+x.arrAbs)+TURN72+90,bDep=(+nx.depAbs)-TURN72-90-dB;\n        if(bDep<hDep+dH+TURN72)continue;          /* 來不及回台北再飛回去就不切 */\n        var h=ferryRow72(st,'TPE',hDep+base927,++sq927);h.depAbs=hDep;h.arrAbs=hDep+dH;h.splitR927=1;h.ferryR131=true;\n        var g=ferryRow72('TPE',st,bDep+base927,++sq927);g.depAbs=bDep;g.arrAbs=bDep+dB;g.splitR927=1;g.ferryR131=true;\n        cur.push(h);out927.push(cur);cur=[g];n927++;\n      }\n      if(cur.length)out927.push(cur);\n    });\n    blocks=out927;\n    window.KGM_SPLIT_R927=window.KGM_SPLIT_R927||{};window.KGM_SPLIT_R927[type]=n927;\n  })();\n");
/* ── 0927B · r147 補調機前先檢查會不會跟這架飛機現有的航段重疊 ── */
RL('r147 no-overlap guard','kgm-0907a-r147',"    out.rows.push(j.tail+' '+date+' '+rec.code+' '+fr+'\\u2192'+to+' '+rec.dep+'-'+rec.arr+(dd?' +'+dd:''));\n    if(apply){",
"    /* 0927B：這一支在載入後 95／125 秒自動補調機。排班剛重建完（例如後台按「重排」）還沒統一時間軸時，\n       它用 depAbs 排序會看到假的跳接，補出來的調機跟下一班重疊（0927A 實測一次 45 段重疊）。\n       這也是「修補步驟沒有檢查落地到起飛間隔」的同一類問題：插進去之前，用時刻表的真實時間\n       （含日光節約）逐段比對這架飛機現有的航段，前後各留 55 分鐘過站，會重疊就不插。 */\n    try{\n      /* 先用真實時間排一次：p 真正的下一段如果本來就從 p 的落點起飛，這個「跳接」只是排序軸不一致造成的假象，不補。 */\n      var tt927=function(r2,w){return _fUTC(Object.assign({},r2,{fr:FR147(r2),to:TO147(r2)}),r2.date,w)};\n      var pT=tt927(p,'dep'),nxt927=null,nT=Infinity;\n      (TA[j.tail]||[]).forEach(function(r2){if(!sane147(r2)||r2===p)return;var d2=tt927(r2,'dep');if(isFinite(d2)&&d2>pT&&d2<nT){nT=d2;nxt927=r2}});\n      if(nxt927&&sta147(FR147(nxt927))===sta147(TO147(p))){out.skipped.push({tail:j.tail,at:j.at,why:'fake-jump-R927'});return}\n      var fA=_fUTC(rec,rec.date,'dep'),fB=_fUTC(rec,rec.date,'arr');\n      var clash927=(TA[j.tail]||[]).some(function(r2){\n        if(!sane147(r2)||r2===p||r2===q)return false;\n        var a2=_fUTC(Object.assign({},r2,{fr:FR147(r2),to:TO147(r2)}),r2.date,'dep'),b2=_fUTC(Object.assign({},r2,{fr:FR147(r2),to:TO147(r2)}),r2.date,'arr');\n        return isFinite(a2)&&isFinite(b2)&&a2<fB+55&&b2+55>fA;\n      });\n      var pB=_fUTC(Object.assign({},p,{fr:FR147(p),to:TO147(p)}),p.date,'arr'),qA=_fUTC(Object.assign({},q,{fr:FR147(q),to:TO147(q)}),q.date,'dep');\n      if(clash927||(isFinite(pB)&&fA<pB+55)||(isFinite(qA)&&fB+55>qA)){\n        out.skipped.push({tail:j.tail,at:j.at,why:'would-overlap-R927',ferry:rec.dep+'-'+rec.arr+' '+date});\n        return;\n      }\n    }catch(_){}\n    out.rows.push(j.tail+' '+date+' '+rec.code+' '+fr+'\\u2192'+to+' '+rec.dep+'-'+rec.arr+(dd?' +'+dd:''));\n    if(apply){");
/* ── 0927B · B779 44 → 41 架（根本原因修好之後） ── */
RL('b779 41','kgm-0823o-r72',"FLEET_CNT.B779=44;","FLEET_CNT.B779=41;");
RL('b779 comment','kgm-0823o-r72',"（B78X 縮到 12 架實測會出現調機段時間重疊；B779 縮到 40 架會有一段 KX55→KX288 重疊，44 架乾淨）。",
 "（B78X 縮到 12 架實測會出現調機段時間重疊；B779 縮到 40 架會有一段 KX55→KX288 重疊，44 架乾淨）。\n     0927B：KX55→KX288 的重疊是日光節約時區的落地時間算錯（見 durOn72），修好之後 B779 縮到 41 架\n     （連同備用機身共 46 架）：8 個不同起算日整年覆蓋率 100%、輪轉 0 接不上 0 重疊；38 架有 2 個起算日漏班、40 架在 2026-09-27 起算就漏 1 班（A35K KX96），所以停在 41。");
