/* 1007A · 組員班表建置效能：每月執勤日數改為快取 */
RL("perf7 month duty cache","kgm-0903b-r121","if(!p.virtualR121){var mo6=date.slice(0,7),dd6={},n6=0;for(var q6=h.length-1;q6>=0;q6--){var d6=h[q6].date;if(!d6)continue;if(d6.slice(0,7)!==mo6){if(d6<mo6)break;continue}if(!dd6[d6]){dd6[d6]=1;n6++}}if(n6>=(+window.KGM_MONTH_DUTY_MAX_R1006A||20))return false;}","if(!p.virtualR121){var mo6=date.slice(0,7),mc7=st.mc7;if(!mc7||mc7.n!==h.length||mc7.mo!==mo6||mc7.h!==h){var dd6={},n6=0;for(var q6=h.length-1;q6>=0;q6--){var d6=h[q6].date;if(!d6)continue;if(d6.slice(0,7)!==mo6){if(d6<mo6)break;continue}if(!dd6[d6]){dd6[d6]=1;n6++}}mc7=st.mc7={n:h.length,mo:mo6,h:h,c:n6}}if(mc7.c>=(+window.KGM_MONTH_DUTY_MAX_R1006A||20))return false;}   /* 1007A：依紀錄筆數＋月份快取（原本每次判斷都整份重掃） */",1);
RL("perf7 engine inv commit","kgm-0903b-r121","var inv=window.kgmCabinInventory54(m,m.date,c)","var inv=(window.kgmDhInvR1007A||window.kgmCabinInventory54)(m,m.date,c)",1);
RL("perf7 engine inv release","kgm-0903b-r121","var inv=window.kgmCabinInventory54(m,date,c)","var inv=(window.kgmDhInvR1007A||window.kgmCabinInventory54)(m,date,c)",1);
RL("perf7 early cheap rejects","kgm-0903b-r121","  function eligible(p,f,rank,ignoreLocation){\n    if(rank&&p.rank!==rank)return false;\n","  function eligible(p,f,rank,ignoreLocation){\n    if(rank&&p.rank!==rank)return false;\n    var st0=history(p),h0=st0.days;if(h0.length&&h0[h0.length-1].date===date)return false;if(st0.ready>f.depUTC-60)return false;   /* 1007A：最常見的兩個不合格原因先判（下方原本的判斷照舊保留） */\n",1);
RL("perf7 sums after cheap checks","kgm-0903b-r121","    var total=sums[h.length],week=total-sums[after(f.depUTC-7*1440,'dep')],month=total-sums[after(f.depUTC-30*1440,'dep')],year=total-sums[after(f.depUTC-365*1440,'dep')],cursor=release-7*1440,longRest=0;\n    for(var hi=after(cursor,'release');hi<h.length;hi++){var x=h[hi];longRest=Math.max(longRest,x.report-cursor);cursor=Math.max(cursor,x.release)}\n\n    longRest=Math.max(longRest,report-cursor);\n","",1);
RL("perf7 sums moved","kgm-0903b-r121","    if(_cm+f.block>LAW.month100)return false;\n    return week+f.block<=LAW.roll7d","    if(_cm+f.block>LAW.month100)return false;\n    var total=sums[h.length],week=total-sums[after(f.depUTC-7*1440,'dep')],month=total-sums[after(f.depUTC-30*1440,'dep')],year=total-sums[after(f.depUTC-365*1440,'dep')],cursor=release-7*1440,longRest=0;\n    for(var hi=after(cursor,'release');hi<h.length;hi++){var x=h[hi];longRest=Math.max(longRest,x.report-cursor);cursor=Math.max(cursor,x.release)}\n    longRest=Math.max(longRest,report-cursor);\n    return week+f.block<=LAW.roll7d",1);
RL("perf7 fullweek cache","kgm-0903b-r121","    add({date:d});(extra||[]).forEach(add);\n    var h=st.days||[];for(var i=Math.max(0,h.length-16);i<h.length;i++)add(h[i]);\n    /* r196 換人／補班加上去的勤務日（r121 自己的紀錄裡沒有） */\n    var ex=id&&window.KGM_EXTRA_DUTY_R927D&&window.KGM_EXTRA_DUTY_R927D[id];if(ex)Object.keys(ex).forEach(function(k){add({date:k})});\n    return n>=7;\n","    /* 1007A：沒有額外調位日（extra）時，「紀錄最後 16 筆落在這一週的不同日期」依（紀錄、筆數、週一）快取，結果與下方原算法相同 */\n    var h=st.days||[];\n    if(!(extra&&extra.length)){var fw=st.fw7;if(!fw||fw.h!==h||fw.n!==h.length||fw.w0!==w0){var s7={},c7=0;for(var i7=Math.max(0,h.length-16);i7<h.length;i7++){var y7=h[i7];if(y7&&y7.date&&y7.date>=w0&&y7.date<=w1&&!s7[y7.date]){s7[y7.date]=1;c7++}}fw=st.fw7={h:h,n:h.length,w0:w0,s:s7,c:c7}}\n      var n7=1+fw.c-(fw.s[d]?1:0),ex7=id&&window.KGM_EXTRA_DUTY_R927D&&window.KGM_EXTRA_DUTY_R927D[id];\n      if(ex7)for(var k7 in ex7){if(k7&&k7>=w0&&k7<=w1&&k7!==d&&!fw.s[k7])n7++}\n      return n7>=7;}\n    add({date:d});(extra||[]).forEach(add);\n    for(var i=Math.max(0,h.length-16);i<h.length;i++)add(h[i]);\n    /* r196 換人／補班加上去的勤務日（r121 自己的紀錄裡沒有） */\n    var ex=id&&window.KGM_EXTRA_DUTY_R927D&&window.KGM_EXTRA_DUTY_R927D[id];if(ex)Object.keys(ex).forEach(function(k){add({date:k})});\n    return n>=7;\n",1);
RL("perf7 first tail date cache","kgm-0908B-r210","    function firstTailDate914(){\n      var f=null;\n      try{\n","    var FT7=null,FTK7=null,FTS7=null;   /* 1007A：班表第一天的快取 —— 原本每查一天的航班就把整份機隊（上萬段）掃一遍 */\n    function firstTailDate914(){\n      var k7=null;try{k7=(window.kgmRosterStampR121?window.kgmRosterStampR121():null);if(k7!==null)k7=k7+'|'+T()}catch(_){k7=null}\n      if(k7!==null&&FTS7===S.tailAssign&&FTK7===k7)return FT7;   /* 機隊物件與逐架航段數指紋（排班引擎自己的失效判斷）都沒變才沿用 */\n      var f=null;\n      try{\n",1);
RL("perf7 first tail date store","kgm-0908B-r210","          if(x&&x.date&&(f===null||x.date<f))f=x.date})});\n      }catch(_){}\n      return f;\n    }","          if(x&&x.date&&(f===null||x.date<f))f=x.date})});\n      }catch(_){}\n      FT7=f;FTK7=k7;FTS7=S.tailAssign;\n      return f;\n    }",1);
RL("perf7 lazy remaining","kgm-0903b-r121","var remaining=(buckets[fam121(f.type)+'|'+role]||[]).filter(function(p){return !used[p.empId]&&!_inL921[p.empId]&&eligible(p,f,rank,true)}).sort(function(a,b){return monthLoads[a.empId]-monthLoads[b.empId]});for(var k=0,tr6=0;k<remaining.length&&list.length<n&&tr6<24;k++){tr6++;if(reposition(remaining[k],f))list.push(remaining[k])}}","var remaining=(buckets[fam121(f.type)+'|'+role]||[]).filter(function(p){return !used[p.empId]&&!_inL921[p.empId]}).sort(function(a,b){return monthLoads[a.empId]-monthLoads[b.empId]});for(var k=0,tr6=0;k<remaining.length&&list.length<n&&tr6<24;k++){if(!eligible(remaining[k],f,rank,true))continue;tr6++;if(reposition(remaining[k],f))list.push(remaining[k])}}   /* 1007A：先排序、逐一判資格，試滿 24 位就停（穩定排序，挑到的人與原本「全部判完再排序」完全相同；原本人手不足時整個機型幾千人每位都判一次） */",1);
RL("perf7 cursor start plan","kgm-0903b-r121","if(!CURSOR121){var first=date;","if(!CURSOR121){var first=date;try{var h7=D(T(),-30);if(h7<first)first=h7}catch(_){}   /* 1007A：至少從今天往前 30 天開始（組員歷史） */\n  ",1);
RL("perf7 cursor start step","kgm-0903b-r121","var first=T();Object.keys(S.tailAssign||{})","var first=T();try{var h7=D(T(),-30);if(h7<first)first=h7}catch(_){}   /* 1007A：同上 */\n  Object.keys(S.tailAssign||{})",1);
RL("perf7 need day = cursor start","kgm-0908B-r210","NEED6={};NEED6[k]=first","NEED6={};var h7=D(T(),-30);NEED6[k]=(first<h7?first:h7)",1);
RL("perf7 r216 range 75","kgm-0908B-r216","(x.ground<90||x.ground>105)","(x.ground!==75)",3);
RL("perf7 r216 msg 75","kgm-0908B-r216","第五航權中停仍未落在 90–105 分鐘 (","第五航權中停不是 75 分鐘（1006A 起一律 75 分）(",1);
