/* 1006A · 座位：選走就是選走 */
RL("r30 export shift","kgm-0816a-r30","window.kgmEconOffsetR30=offsetOf;","window.kgmEconOffsetR30=offsetOf;\n/* 1006A：給訂位選位圖、行程管理選位、自動配位共用的換號（舊號＝選位圖原始排號，新號＝客艙圖排號） */\nwindow.kgmSeatShiftR1006A=function(f){\n  var a=f&&f.acft;try{if(f&&f.code&&f.date)a=acftOfFlight(f.code,f.date)||a}catch(_){}\n  var p=PLAN30[a],b=p&&bookEconBase(a);\n  return b?{start:b.start,end:b.end,off:p.econStart-b.start}:null;\n};\nwindow.kgmShownSeatR1006A=function(f,sid){\n  var x=window.kgmSeatShiftR1006A(f);if(!x||!x.off)return sid;\n  var r=parseInt(sid,10),c=String(sid).replace(/[0-9]/g,'');\n  return (r>=x.start&&r<=x.end)?(r+x.off)+c:sid;\n};\nwindow.kgmRawSeatR1006A=function(f,sid){\n  var x=window.kgmSeatShiftR1006A(f);if(!x||!x.off)return sid;\n  var r=parseInt(sid,10),c=String(sid).replace(/[0-9]/g,'');\n  return (r>=x.start+x.off&&r<=x.end+x.off)?(r-x.off)+c:sid;\n};",1);
R("book map split taken","var _takenSeatMap={};\n  try{Object.assign(_takenSeatMap,simSeatMap(f.code,f.date)||{});}catch(_ts1){}\n  try{if(typeof realTakenSeats0814===\"function\")Object.assign(_takenSeatMap,realTakenSeats0814(f,S.seatChangePnr||(S.mgResult&&S.mgResult.pnr)));}catch(_ts2){}","var _takenSeatMap={},_simTaken6={},_realTaken6={};\n  try{_simTaken6=simSeatMap(f.code,f.date)||{};Object.assign(_takenSeatMap,_simTaken6);}catch(_ts1){}\n  try{if(typeof realTakenSeats0814===\"function\"){_realTaken6=realTakenSeats0814(f,S.seatChangePnr||(S.mgResult&&S.mgResult.pnr))||{};Object.assign(_takenSeatMap,_realTaken6);}}catch(_ts2){}",1);
R("book map occupied by shown id","const isSel=!!sel[sid];\n        const isOccupied=!!_takenSeatMap[sid]&&!isSel;","/* 1006A：經濟艙改號後，已選／被選走都用改號後的號碼比對（真實訂位存的就是這個號碼） */\n        const _sid6=(cabinName===\"Economy\"&&window.kgmShownSeatR1006A)?window.kgmShownSeatR1006A(f,sid):sid;\n        const isSel=!!sel[_sid6];\n        const isOccupied=(_sid6===sid?!!_takenSeatMap[sid]:(!!_simTaken6[sid]||!!_realTaken6[_sid6]))&&!isSel;",1);
R("manage layout shown rows","return {tp:tp,ac:ac,cabin:cabin,key:key,cfg:(cb[key]||{}).cfg||'',lay:(cb[key]||{}).lay||[],rows:(cb[key]||{}).rows||0,start:start};","var off6=0;if(key==='econ'&&window.kgmSeatShiftR1006A){var x6=window.kgmSeatShiftR1006A(f);if(x6&&x6.start===start)off6=x6.off;}/* 1006A：經濟艙用客艙圖排號 */\n  return {tp:tp,ac:ac,cabin:cabin,key:key,cfg:(cb[key]||{}).cfg||'',lay:(cb[key]||{}).lay||[],rows:(cb[key]||{}).rows||0,start:start+off6,off:off6};",1);
R("manage page sim raw id","var sid=String(rn)+col,mine=!!d[sid],taken=(!!sim[sid]||!!real[sid])&&!mine;","var sid=String(rn)+col,mine=!!d[sid],taken=(!!sim[li.off?String(rn-li.off)+col:sid]||!!real[sid])&&!mine;",1);
R("auto assign shown ids","  var preferred=ids.filter(function(sid){return !real[sid]&&!sim[sid]&&!bk.seats[seg][sid];});\n  var fallback=ids.filter(function(sid){return !real[sid]&&!bk.seats[seg][sid];});","  var sh6=function(sid){return window.kgmShownSeatR1006A?window.kgmShownSeatR1006A(f,sid):sid};/* 1006A：真實訂位用改號後的號碼 */\n  var preferred=ids.filter(function(sid){return !real[sh6(sid)]&&!sim[sid]&&!bk.seats[seg][sh6(sid)];});\n  var fallback=ids.filter(function(sid){return !real[sh6(sid)]&&!bk.seats[seg][sh6(sid)];});",1);
R("auto assign store shown","while(selected.length<pax&&pool.length){var ix=(h+selected.length*7919)%pool.length,sid=pool.splice(ix,1)[0];bk.seats[seg][sid]=true;selected.push(sid);}","while(selected.length<pax&&pool.length){var ix=(h+selected.length*7919)%pool.length,sid=sh6(pool.splice(ix,1)[0]);bk.seats[seg][sid]=true;selected.push(sid);}",1);
RL("r65 sim shown","kgm-0823k-r65","    var sim=(typeof simSeatMap==='function')?simSeatMap(seg.f.code,seg.date):{};\n    Object.keys(sim||{}).forEach(function(k){if(k)t[String(k).toUpperCase()]=1});","    var sim=(typeof simSeatMap==='function')?simSeatMap(seg.f.code,seg.date):{};\n    var f6=Object.assign({},seg.f,{date:seg.date});/* 1006A：模擬佔位換成客艙圖排號 */\n    Object.keys(sim||{}).forEach(function(k){if(k)t[String(window.kgmShownSeatR1006A?window.kgmShownSeatR1006A(f6,k):k).toUpperCase()]=1});",1);
RL("r30 keep taken title","kgm-0816a-r30","var title=lk?(z()?'不可選':'Unavailable'):sid;","var title=lk?(/已被其他訂位選走|Taken by another booking/.test(el.getAttribute('title')||'')?el.getAttribute('title'):(z()?'不可選':'Unavailable')):sid;/* 1006A：被選走的位子保留「已被其他訂位選走」 */",1);
