/* 1006A · 登機門平均分配、不重疊、外站也有門；季節限定航段 */
RL("gate allowed list from stands","kgm-0909E-r229","  function allowed9(ap,tp,term){\n    var all=stands9(ap);","  function allowed9(ap,tp,term){\n    var all=[];try{all=(window.kgmStandsForR100&&window.kgmStandsForR100(ap,tp))||[]}catch(_){all=[]}   /* 1006A：機型停得下的位子；外站沒有 AP_GATES 也有門可配 */\n    if(!all.length)all=stands9(ap);",1);
RL("gate least-used pick","kgm-0909E-r229","      for(i=0;i<opts.length;i++)if(free(opts[i],r)){pick=opts[i];break}","      /* 1006A：空著的門裡挑當天用得最少的（遠端機位稍後），同分依班號錯開 —— 不再永遠先塞前面幾個門 */\n      var h6=2166136261,s6=String(r.code)+'|'+date,bs6=1e9;for(i=0;i<s6.length;i++){h6^=s6.charCodeAt(i);h6=Math.imul(h6,16777619)>>>0}\n      for(i=0;i<opts.length;i++){var g6=opts[(i+h6)%opts.length];if(!free(g6,r))continue;\n        var sc6=(busy[g6]||[]).length*10+(/R$/.test(g6)?15:0);if(sc6<bs6){bs6=sc6;pick=g6}}",1);
RL("gate overflow list","kgm-0909E-r229","        var all2=stands9(ap);","        var all2=stands9(ap);if(!all2.length)try{all2=window.kgmStandsForR100(ap,'B789')||[]}catch(_){all2=[]}",1);
RL("timetable window helper","kgm-0823k-r65","function gateTimetable65(){","/* 1006A：佔用時間跟配位器同一份（A380 起飛前 120 分、廣體 90 分、窄體 60 分，至起飛後 15 分） */\nfunction gw6(f,date){try{var a=window.kgmGateAllocR922&&window.kgmGateAllocR922(f.fr,date);var r=a&&a.rows.filter(function(x){return x.code===f.code&&x.fr===f.fr&&x.to===f.to})[0];if(r)return mn(f.dep)-r.start}catch(_){}return 90}\nfunction gateTimetable65(){",1);
RL("timetable window use","kgm-0823k-r65","from:hm(d-90),to:hm(d+15)});","from:hm(d-gw6(f,date)),to:hm(d+15)});",2);
RL("timetable text","kgm-0823k-r65","佔用時間（起飛前 90 分鐘至起飛後 15 分鐘）","佔用時間（起飛前地面作業至起飛後 15 分鐘：A380 120 分、廣體 90 分、窄體 60 分；同一個門兩班之間至少隔 10 分鐘）",1);
R("flyOn season-only legs","function flyOn(f,d){\n  if(typeof S!==\"undefined\"&&S.flightDisabled","function flyOn(f,d){\n  if(f&&f.seasonOnlyR126&&!(f.mon&&f.mon.length)&&typeof window!==\"undefined\"&&window.kgmSeasonKeepR126&&d&&d.getFullYear){var _s6=d.getFullYear()+\"-\"+String(d.getMonth()+1).padStart(2,\"0\")+\"-\"+String(d.getDate()).padStart(2,\"0\");if(!window.kgmSeasonKeepR126(f,_s6))return false;}/* 1006A：季節限定航段只在那一季飛 */\n  if(typeof S!==\"undefined\"&&S.flightDisabled",1);
RL("planned gate pass ap","kgm-0823k-r65","kgmGatePlannedR65=function(code,date){\n  var g=null;\n  try{S._k65Raw=1;g=window.kgmGateOfR26(code,date)}","kgmGatePlannedR65=function(code,date,ap){\n  var g=null;\n  try{S._k65Raw=1;g=window.kgmGateOfR26(code,date,ap)}",1);
RL("timetable pass ap","kgm-0823k-r65","window.kgmGatePlannedR65(f.code,date)","window.kgmGatePlannedR65(f.code,date,ap)",3);
RL("front gate pass ap","kgm-0814d-r22","window.kgmGateR22=function(code,date){","window.kgmGateR22=function(code,date,ap){   /* 1006A：ap＝出發機場（第五航權同班號兩段各有自己的門） */",1);
RL("front gate pass ap 2","kgm-0814d-r22","try{var r=window.kgmGateOfR26(code,date);","try{var r=window.kgmGateOfR26(code,date,ap);",1);
RL("trip card gate ap r25","kgm-0814d-r25","window.kgmGateR22(sg.code,sg.date)","window.kgmGateR22(sg.code,sg.date,sg.fr)",1);
RL("trip card gate ap r52","kgm-0823b-r52","window.kgmGateR22(s.code,s.date)","window.kgmGateR22(s.code,s.date,(s.fr||(s.f&&s.f.fr)||''))",1);
RL("r100 flight = departing leg","kgm-0902a-r100","    out.flight=out.flight||f;","    out.flight=f;   /* 1006A：同班號兩段時 base 帶的是第一段（TPE），要用這次查的出發機場那一段 */",1);
