/* 1004A · 組員（航班組員查詢、組員班表、客艙編制…） */
RL("crew legs fn","kgm-0903b-r121","    W.__r121=1;window.kgmCrewOfR43=W;","    W.__r121=1;window.kgmCrewOfR43=W;\n    /* 1004A：同一班號的每一段（KX20 台北→成田、成田→檀香山；KX19 檀香山→成田、隔天成田→台北）都列出來。\n       原本只取當天排班裡的第一筆，第五航權後段的組員查不到。隔天才續飛的後段依 kgmViaOriginR929 歸回出發日。 */\n    window.kgmCrewLegsR929=function(code,date){\n      /* 1004A：日期必須是 YYYY-MM-DD。空字串時 addDays 會得到 \"NaN-NaN-NaN\"，字串比較大於任何日期，\n         kgmCrewPlanR121 會一路往未來排、停不下來（kgmAuditR97 → 餐點統計因此卡死）。不合法就走原本的查法。 */\n      if(!/^\\d{4}-\\d\\d-\\d\\d$/.test(String(date||'')))return null;\n      var out=[];\n      function take(d,own){\n        try{(window.kgmCrewPlanR121(d).flights||[]).forEach(function(r){\n          if(r.code!==code||r.positioning||!(r.pilots||[]).length)return;\n          var p=String(r.route||'').split('→'),o=window.kgmViaOriginR929?window.kgmViaOriginR929(code,p[0],p[1],d):null;\n          if(own?(o&&o.date!==date):!(o&&o.date===date))return;\n          out.push(Object.assign({},r,{dateR929:d}));\n        })}catch(_){}\n      }\n      take(date,true);take(addDays(date,1),false);\n      out.sort(function(a,b){return String(a.dateR929+a.dep).localeCompare(String(b.dateR929+b.dep))});\n      return out;\n    };",1);
RL("crew query legs","kgm-0817b-r43","      var c=window.kgmCrewOfR43(code,date);\n      if(c){\n        var row={seg:1,route:c.route,acft:c.type,tail:c.tail,","      try{\n        var legs929=window.kgmCrewLegsR929?window.kgmCrewLegsR929(code,date):null;\n        if(legs929&&legs929.length>1){\n          var rows929=legs929.map(function(r,i){return {seg:i+1,leg:i+1,route:r.route,acft:r.type,tail:r.tail,dateR929:r.dateR929,\n            pilots:r.pilots.map(function(p){return {rank:p.rank,name:p.name,empId:p.empId}}),\n            cabin:(r.cabin||[]).map(function(p){return {rank:p.rank,name:p.name,empId:p.empId}})}});\n          return {roster:rows929,sched:rows929,synth:[],sourceR43:true,viaR929:true};   /* 1004A：第五航權每一段 */\n        }\n      }catch(_){}\n      var c=window.kgmCrewOfR43(code,date);\n      if(c){\n        var row={seg:1,route:c.route,acft:c.type,tail:c.tail,",1);
R("cabin std","  var extra=wide?2:1;\n  return {type:t,seats:seats,legal:legal,extra:extra,crew:legal+extra};","  var extra=wide?2:1;\n  /* 1004A：使用者：「組員不夠，TPE–YVR B777 只有 10 個、1 個座艙長；實務上長程 B777 大約 16 個」。\n     法規下限＋1～2 只是底線；再加上各機型的服務編制（長程），取兩者較大者。短程由排班端打八折（不低於法規＋1～2）。 */\n  var STD929={A388:24,B779:16,A35K:14,B78X:13,A359:13,B789:12,A339:11,A339L:11,A339R:11,A21N:6};\n  var std=STD929[t]||STD929[t.replace(/[LR]$/,'')]||0;\n  return {type:t,seats:seats,legal:legal,extra:extra,std:std,crew:Math.max(legal+extra,std)};",1);
RL("cabin short","kgm-0903b-r121","function cabinSize121(type){","/* 1004A：短程（航段 5 小時以內）客艙打八折，不低於法規下限＋1～2 */\nfunction cabinFor929(f){\n  var full=cabinSize121(f.type);\n  try{if((+f.block||0)<300){var k=window.kgmCabinCrewR927(String(f.type||'').toUpperCase());return Math.max(k.legal+k.extra,Math.ceil(full*0.8))}}catch(_){}\n  return full;\n}\nwindow.kgmCabinForR929=cabinFor929;\nfunction cabinSize121(type){",1);
RL("cabin short use","kgm-0903b-r121","    var comp=window.kgmPilotComplementR121(f.block,f.type),cabN=f.positioning?0:cabinSize121(f.type),used={},pilots=[],cabin=[],fdp=f.block+90;","    var comp=window.kgmPilotComplementR121(f.block,f.type),cabN=f.positioning?0:cabinFor929(f),used={},pilots=[],cabin=[],fdp=f.block+90;",1);
RL("cabin ranks","kgm-0903b-r121","      cabin=choose(f,'cabin',null,cabN,used);","      /* 1004A：一位座艙長＋依人數配副座艙長（各艙區帶班），其餘空服員；座艙長／副座艙長不足時由其他人補滿人數 */\n      var nD929=cabN>=20?4:cabN>=14?3:cabN>=10?2:cabN>=5?1:0,pu929=cabN?choose(f,'cabin','PU',1,used):[],dp929=nD929?choose(f,'cabin','DPU',nD929,used):[];\n      var more929=Math.max(0,cabN-pu929.length-dp929.length),fa929=more929?choose(f,'cabin','FA',more929,used):[];more929-=fa929.length;\n      var up929=more929>0?choose(f,'cabin','DPU',more929,used):[];more929-=up929.length;   /* 空服員不夠才由副座艙長、再不夠才由任何人補 */\n      cabin=pu929.concat(dp929,fa929,up929,more929>0?choose(f,'cabin',null,more929,used):[]);",1);
RL("crew initial real first","kgm-0903b-r121","      _sk921.set(p,{t:(h.length&&h[h.length-1].date===date)?0:1,i:st.initial?1:0})});","      _sk921.set(p,{t:(h.length&&h[h.length-1].date===date)?0:1,i:(st.initial&&p.virtualR121)?1:0})});   /* 1004A：原本「還沒飛過」的一律排最後，一開始沒被挑到的真人就永遠輪不到（實測 5 位 A380 正機師 30 天全空、班都給了虛擬人員）；只有虛擬人員排最後 */",1);
RL("roster no same-city dh","kgm-0907A-r196","  function dhLegs196(x){return (x.legs||[]).filter(isDh196)}","  /* 1004A：同城機場之間（TPE／TSA、ICN／GMP、NRT／HND…）是地面轉場，不是「以旅客身分調位」，班表上不寫 */\n  var SC929={TPE:'TPE',TSA:'TPE',NRT:'TYO',HND:'TYO',KIX:'OSA',UKB:'OSA',ICN:'SEL',GMP:'SEL',PVG:'SHA',SHA:'SHA',LAX:'LAX',ONT:'LAX',HKG:'HKG',MFM:'HKG',BKK:'BKK',DMK:'BKK'};\n  function sameCity929(l){return !!(l&&(l.surfaceR928||(SC929[l.fr]&&SC929[l.fr]===SC929[l.to])))}\n  function dhLegs196(x){return (x.legs||[]).filter(function(l){return isDh196(l)&&!sameCity929(l)})}",1);
RL("pin first in choose","kgm-0903b-r121","      if(pinL.length){var pk={};pinL.forEach(function(p){pk[p.empId]=1});list=pinL.concat(list.filter(function(p){return !pk[p.empId]}))}}","      if(pinL.length){var pk={};pinL.forEach(function(p){pk[p.empId]=1;_pin929[p.empId]=1});list=pinL.concat(list.filter(function(p){return !pk[p.empId]}))}}",1);
RL("pin map decl","kgm-0903b-r121","    if(PIN928){var pinL=","    var _pin929={};   /* 1004A：指定（換班／已公布凍結）飛這一班的人 */\n    if(PIN928){var pinL=",1);
RL("pin first in sort","kgm-0903b-r121","    list.sort(function(a,b){\n      var ka=_sk921.get(a)||{t:1,i:1},kb=_sk921.get(b)||{t:1,i:1};\n      return ka.t-kb.t||","    /* 1004A：「指定飛這一班的人排最前面」原本只是先放在名單前面，下一行的排序又把整份名單重排，\n       被指定的人常被擠出前 n 名 —— 實測 0928B 的 AI 換班，被換過去的那一位幾乎每次都排不上（引擎資格檢查其實是通過的）。\n       排序第一個鍵改成「是否被指定」，其餘規則一字不改。 */\n    list.sort(function(a,b){\n      var ka=_sk921.get(a)||{t:1,i:1},kb=_sk921.get(b)||{t:1,i:1};\n      return (_pin929[a.empId]?0:1)-(_pin929[b.empId]?0:1)||ka.t-kb.t||",1);
